#!/bin/sh
### BEGIN INIT INFO
# Provides:         teamspeak3
# Required-Start:     $local_fs $network
# Required-Stop:    $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:     0 1 6
# Description:         Teamspeak 3 Server
### END INIT INFO
# INIT Script by wiki.xprog.de
######################################
case "$1" in
start)
su ts3user -c "/usr/local/ts3user/ts3server/ts3server_startscript.sh start"
;;
stop)
su ts3user -c "/usr/local/ts3user/ts3server/ts3server_startscript.sh stop"
;;
restart)
su ts3user -c "/usr/local/ts3user/ts3server/ts3server_startscript.sh restart"
;;
status)
su ts3user -c "/usr/local/ts3user/ts3server/ts3server_startscript.sh status"
;;
*)
echo "Usage: {start|stop|restart|status}" >&2
exit 1
;;
esac
exit 0